# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-26 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0003_auto_20170419_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='annotation',
            field=models.TextField(blank=True, verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='github_account',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Github Account'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='invite_email',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='Invite_email'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Invite token'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
