# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-26 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_sponsorship', '0002_auto_20160517_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
    ]
